name: Bug report
description: File a bug report to help us improve
labels: [bug]
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do we reproduce the bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or logs
      description: Add any relevant screenshots or logs.
    validations:
      required: false
