"""create loyalty model

Revision ID: 2348f16dd92f
Revises: 452a0ec67e0c
Create Date: 2025-07-11 08:53:04.450937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2348f16dd92f'
down_revision = '452a0ec67e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan_memberships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_tag', sa.String(length=15), nullable=True),
    sa.Column('clan_tag', sa.String(length=15), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_tag', 'clan_tag', 'joined_at', name='uq_clan_membership')
    )
    with op.batch_alter_table('clan_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clan_memberships_clan_tag'), ['clan_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_memberships_player_tag'), ['player_tag'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clan_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clan_memberships_player_tag'))
        batch_op.drop_index(batch_op.f('ix_clan_memberships_clan_tag'))

    op.drop_table('clan_memberships')
    # ### end Alembic commands ###
