"""empty message

Revision ID: 4211c3ea26a0
Revises: 2348f16dd92f
Create Date: 2025-07-11 16:49:41.480389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4211c3ea26a0'
down_revision = '2348f16dd92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('clan_tag', sa.String(length=15), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clan_tag', 'ts', name='uq_war_ts')
    )
    with op.batch_alter_table('war_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_war_snapshots_clan_tag'), ['clan_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_snapshots_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('war_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_war_snapshots_ts'))
        batch_op.drop_index(batch_op.f('ix_war_snapshots_clan_tag'))

    op.drop_table('war_snapshots')
    # ### end Alembic commands ###
