"""add last_seen to player snapshot

Revision ID: 452a0ec67e0c
Revises: c50b95df90c9
Create Date: 2025-07-09 14:22:33.190607

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "452a0ec67e0c"
down_revision = "c50b95df90c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_seen", sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_player_snapshots_last_seen"), ["last_seen"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_snapshots_last_seen"))
        batch_op.drop_column("last_seen")

    # ### end Alembic commands ###
