"""empty message

Revision ID: 8b286b37f399
Revises: e3278e06d537
Create Date: 2025-09-08 11:33:55.106765

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '8b286b37f399'
down_revision = 'e3278e06d537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['from_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['to_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
