"""initial schema

Revision ID: aa57484c84ef
Revises:
Create Date: 2025-07-08 17:10:44.932310

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aa57484c84ef"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clan_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=True),
        sa.Column("clan_tag", sa.String(length=15), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("war_wins", sa.Integer(), nullable=True),
        sa.Column("war_losses", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clan_tag", "ts", name="uq_clan_ts"),
    )
    with op.batch_alter_table("clan_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_clan_snapshots_clan_tag"), ["clan_tag"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_clan_snapshots_ts"), ["ts"], unique=False)

    op.create_table(
        "player_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=True),
        sa.Column("player_tag", sa.String(length=15), nullable=True),
        sa.Column("clan_tag", sa.String(length=15), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("town_hall", sa.Integer(), nullable=True),
        sa.Column("trophies", sa.Integer(), nullable=True),
        sa.Column("donations", sa.Integer(), nullable=True),
        sa.Column("donations_received", sa.Integer(), nullable=True),
        sa.Column("war_attacks_used", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_tag", "ts", name="uq_player_ts"),
    )
    with op.batch_alter_table("player_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_player_snapshots_clan_tag"), ["clan_tag"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_player_snapshots_player_tag"), ["player_tag"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_player_snapshots_ts"), ["ts"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_snapshots_ts"))
        batch_op.drop_index(batch_op.f("ix_player_snapshots_player_tag"))
        batch_op.drop_index(batch_op.f("ix_player_snapshots_clan_tag"))

    op.drop_table("player_snapshots")
    with op.batch_alter_table("clan_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_clan_snapshots_ts"))
        batch_op.drop_index(batch_op.f("ix_clan_snapshots_clan_tag"))

    op.drop_table("clan_snapshots")
    # ### end Alembic commands ###
