"""strip hash from tags + add players table

Revision ID: c50b95df90c9
Revises: aa57484c84ef
Create Date: 2025-07-08 17:33:17.623370

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c50b95df90c9"
down_revision = "aa57484c84ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("tag", sa.String(length=15), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("town_hall", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("clan_tag", sa.String(length=15), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("tag"),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_players_clan_tag"), ["clan_tag"], unique=False
        )

    conn = op.get_bind()
    conn.execute(
        sa.text("""
                         UPDATE clan_snapshots
                         SET clan_tag = ltrim(clan_tag, '#');
                         UPDATE player_snapshots
                         SET clan_tag = ltrim(clan_tag, '#');
                         UPDATE player_snapshots
                         SET player_tag = ltrim(player_tag, '#');
                         """)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_players_clan_tag"))

    op.drop_table("players")
    # ### end Alembic commands ###
