name: CI

on:
  pull_request:

# Token scopes needed by enable-pull-request-automerge
permissions:
  contents: write
  pull-requests: write

jobs:
  nox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install nox
        run: pip install nox

      - name: Run nox
        run: nox -s lint tests smoke

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PR_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
