name: CI

on:
  pull_request:

# Token scopes needed by enable-pull-request-automerge
permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  nox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install nox
        run: pip install nox

      - name: Run nox
        run: nox -s lint tests

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PR_TOKEN }} 
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
